wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    code_path: code/Modern_Implementations/MuJoCo/Testing/S_L_CartPole_DDPG_main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1646625256
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      - 16
      4: 3.9.10
      5: 0.12.7
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 10
debug:
  desc: null
  value: false
discount:
  desc: null
  value: 0.99
do_eval:
  desc: null
  value: false
env:
  desc: null
  value: CartPole-v0
epsilon:
  desc: null
  value: 50000
frate:
  desc: null
  value: 30
hidden1:
  desc: null
  value: 400
hidden2:
  desc: null
  value: 300
init_w:
  desc: null
  value: 0.003
lrate:
  desc: null
  value: 0.001
make_animation:
  desc: null
  value: true
max_episode_length:
  desc: null
  value: 500
max_episode_time:
  desc: null
  value: 1
mode:
  desc: null
  value: train
ou_mu:
  desc: null
  value: 0.0
ou_sigma:
  desc: null
  value: 0.2
ou_theta:
  desc: null
  value: 0.15
output:
  desc: null
  value: output\CartPole-v0-run165
prate:
  desc: null
  value: 0.0001
resume:
  desc: null
  value: output/CartPole-v0-run0
rmsize:
  desc: null
  value: 6000000
seed:
  desc: null
  value: 42
tau:
  desc: null
  value: 0.001
train_iter:
  desc: null
  value: 100000
validate_episodes:
  desc: null
  value: 3
validate_steps:
  desc: null
  value: 1000
wandb:
  desc: null
  value: true
warmup:
  desc: null
  value: 20
window_length:
  desc: null
  value: 1
